# Container uses the official Python 3.9 image as a base.
FROM python:3.9

# All container paths that follow will be relative to this location.
WORKDIR /app

# Copy everything from the backend.
COPY ./backend-flask-server/ ./
RUN pip install -r ./requirements.txt
ENV FLASK_ENV production

EXPOSE 4000
# The gunicorn startup command is module_name:variable_name (common notation for WSGI applications).
CMD ["gunicorn", "-b", ":4000", "app:app"]